name: Build and test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  buildandtest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup .NET Core 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - uses: actions/setup-node@v2
      with:
        node-version: '15'
    - name: Install wait-on globally
      run: npm install -g wait-on     

    - name: Build and run simple test server
      working-directory: "samples/SimpleServer"
      run: |
        dotnet run &
        wait-on http-get://localhost:5000/person/0EB0F488-832F-4144-8492-0CFE73200347
    - name: Test server endpoint
      run: wget http://localhost:5000/person/0EB0F488-832F-4144-8492-0CFE73200347
    
    - name: Build automated tests
      run: dotnet build
      working-directory: "tests/FormSharp.Acceptance.Tests"
    - name: Install playwright
      working-directory: "tests/FormSharp.Acceptance.Tests"        
      run: |
        dotnet tool install --global Microsoft.Playwright.CLI
        playwright install
# playwright install-deps chromium
    
    - name: Install Fable tools
      working-directory: "samples/Fable.React.Tailwind.Sample"
      run: dotnet tool restore
    - name: Install client npm packages
      working-directory: "samples/Fable.React.Tailwind.Sample"
      run: npm install
    - name: Build and run client
      working-directory: "samples/Fable.React.Tailwind.Sample"
      run: |
        dotnet fable watch src --outDir build --run webpack-dev-server &
        wait-on http-get://localhost:8080/
    
    - name: Test server endpoint
      run: wget http://localhost:5000/person/0EB0F488-832F-4144-8492-0CFE73200347
    - name: Test client endpoint
      run: wget http://localhost:8080

    - name: Run tests
      working-directory: "tests/FormSharp.Acceptance.Tests"
      run: dotnet run

    - name: Upload diagnostic screenshot
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: screenshot
        path: tests/FormSharp.Acceptance.Tests/initialpagescreenshot.png
      
    