name: Release NuGet packages
on:
  release:
    types: [created]

# This release script works on the basis that releases are named with the pattern v0.0.0
# which will result in a ref variable of refs/tags/v0.0.0
jobs:
  buildandtest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    
    - name: Setup .NET Core 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    # when working build test step in here

    - name: Package
      run: ./pack.sh "${GITHUB_REF:11}"

    - name: Push
      run: dotnet nuget push "packages/FormSharp.Fable.React.${GITHUB_REF:11}.nupkg" --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json

    - name: Output package as artifact
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: packages
        path: packages/*.nupkg
      
    